FROM aursu/rpmbuild:7-build

USER root
RUN yum -y install \
        openldap-devel \
        krb5-devel \
        libcap-ng-devel \
        doxygen \
        systemtap-sdt-devel \
    && yum clean all && rm -rf /var/cache/yum

RUN yum -y --enablerepo=bintray-custom install \
        bind-export-devel \
        systemd \
        systemd-devel \
        "pkgconfig(libsystemd)" \
    && yum clean all && rm -rf /var/cache/yum
